# Generated by Django 5.1.11 on 2025-07-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('COP', 'Colombian Peso (COP)'), ('GBP', 'British Pound (GBP)'), ('CAD', 'Canadian Dollar (CAD)'), ('AUD', 'Australian Dollar (AUD)'), ('MXN', 'Mexican Peso (MXN)'), ('BRL', 'Brazilian Real (BRL)'), ('ARS', 'Argentine Peso (ARS)'), ('CLP', 'Chilean Peso (CLP)'), ('PEN', 'Peruvian Sol (PEN)'), ('UYU', 'Uruguayan Peso (UYU)'), ('JPY', 'Japanese Yen (JPY)'), ('CNY', 'Chinese Yuan (CNY)'), ('CHF', 'Swiss Franc (CHF)'), ('SEK', 'Swedish Krona (SEK)'), ('NOK', 'Norwegian Krone (NOK)'), ('DKK', 'Danish Krone (DKK)')], default='USD', max_length=3, verbose_name='Currency'),
        ),
    ]
