# Generated by Django 5.1.11 on 2025-07-09 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Company name')),
                ('logo', models.ImageField(blank=True, upload_to='sponsors/logos/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Description')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Contact email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Contact phone')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Is approved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='max_sponsors',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of sponsors for this event. Set to 0 to disable sponsorships.', verbose_name='Max sponsors'),
        ),
        migrations.AddField(
            model_name='event',
            name='sponsorship_open',
            field=models.BooleanField(default=True, help_text='Allow new sponsorship applications', verbose_name='Sponsorship applications open'),
        ),
        migrations.CreateModel(
            name='EventSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('platinum', 'Platinum'), ('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze'), ('partner', 'Partner')], default='partner', max_length=20, verbose_name='Sponsorship tier')),
                ('custom_description', models.TextField(blank=True, help_text="Override sponsor's default description for this event", max_length=300, verbose_name='Custom description')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is featured')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_sponsors', to='events.event')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_events', to='events.sponsor')),
            ],
            options={
                'verbose_name': 'Event Sponsor',
                'verbose_name_plural': 'Event Sponsors',
                'ordering': ['display_order', 'tier', 'sponsor__name'],
                'unique_together': {('event', 'sponsor')},
            },
        ),
        migrations.CreateModel(
            name='SponsorshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company name')),
                ('contact_name', models.CharField(max_length=200, verbose_name='Contact person name')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Contact email')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Contact phone')),
                ('company_website', models.URLField(blank=True, verbose_name='Company website')),
                ('message', models.TextField(help_text='Tell us about your company and why you want to sponsor this event', max_length=1000, verbose_name='Message')),
                ('proposed_tier', models.CharField(choices=[('platinum', 'Platinum'), ('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze'), ('partner', 'Partner')], default='partner', max_length=20, verbose_name='Proposed sponsorship tier')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('contacted', 'Contacted')], default='pending', max_length=20, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for organizers', verbose_name='Admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed at')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorship_applications', to='events.event')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sponsorship Application',
                'verbose_name_plural': 'Sponsorship Applications',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'contact_email')},
            },
        ),
    ]
