# Generated by Django 5.1.11 on 2025-07-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_sponsor_event_max_sponsors_event_sponsorship_open_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='website',
            field=models.CharField(blank=True, max_length=200, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='sponsorshipapplication',
            name='company_website',
            field=models.CharField(blank=True, max_length=200, verbose_name='Company website'),
        ),
    ]
