# Generated by Django 5.1.11 on 2025-07-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendee_feedback_summary',
            field=models.TextField(blank=True, help_text='Summary of attendee feedback and testimonials', verbose_name='Attendee feedback summary'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_highlights',
            field=models.TextField(blank=True, help_text='Key moments and highlights from the event', verbose_name='Event highlights'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_notes',
            field=models.TextField(blank=True, help_text='Private notes for the organizer (not visible to the public)', verbose_name='Organizer notes'),
        ),
        migrations.AddField(
            model_name='event',
            name='post_event_photos',
            field=models.ImageField(blank=True, help_text='Upload photos from the event', upload_to='events/post_event/', verbose_name='Post-event photos'),
        ),
        migrations.AddField(
            model_name='event',
            name='post_event_summary',
            field=models.TextField(blank=True, help_text='Share how the event went, highlights, and memories', verbose_name='Post-event summary'),
        ),
    ]
