# Generated by Django 5.1.11 on 2025-07-15 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_attendee_feedback_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='post_event_photos',
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload photos from the event', upload_to='events/post_event_photos/', verbose_name='Photo')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the photo', max_length=300, verbose_name='Caption')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_photos', to='events.event')),
            ],
            options={
                'verbose_name': 'Event Photo',
                'verbose_name_plural': 'Event Photos',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
