# Generated by Django 5.1.11 on 2025-07-11 04:55

import django.core.validators
import experienciaas.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_organizerprofile_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, help_text='Dirección completa (opcional)', max_length=255, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Imagen de perfil (recomendado: 400x400px)', upload_to='users/avatars/', verbose_name='Foto de perfil'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Cuéntanos un poco sobre ti (máximo 500 caracteres)', max_length=500, verbose_name='Biografía'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Formato: AAAA-MM-DD', null=True, validators=[experienciaas.users.models.validate_birth_date], verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, help_text='Ciudad de residencia', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, help_text='Empresa donde trabajas (opcional)', max_length=100, verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, help_text='País de residencia', max_length=100, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(choices=[('+1', 'Estados Unidos (+1)'), ('+1', 'Canadá (+1)'), ('+52', 'México (+52)'), ('+34', 'España (+34)'), ('+33', 'Francia (+33)'), ('+49', 'Alemania (+49)'), ('+39', 'Italia (+39)'), ('+44', 'Reino Unido (+44)'), ('+54', 'Argentina (+54)'), ('+55', 'Brasil (+55)'), ('+56', 'Chile (+56)'), ('+57', 'Colombia (+57)'), ('+58', 'Venezuela (+58)'), ('+51', 'Perú (+51)'), ('+593', 'Ecuador (+593)'), ('+598', 'Uruguay (+598)'), ('+595', 'Paraguay (+595)'), ('+591', 'Bolivia (+591)')], default='+57', help_text='Selecciona el código de tu país', max_length=5, verbose_name='Código de país'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Recibir notificaciones de eventos por email', verbose_name='Notificaciones por email'),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'Prefiero no decir')], help_text='Esta información es opcional y privada', max_length=1, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='user',
            name='hobbies',
            field=models.TextField(blank=True, help_text='Describe tus hobbies e intereses personales', max_length=300, verbose_name='Hobbies'),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.JSONField(blank=True, default=list, help_text='Selecciona tus áreas de interés para eventos', verbose_name='Intereses'),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='user',
            name='marketing_emails',
            field=models.BooleanField(default=False, help_text='Recibir información sobre eventos y promociones', verbose_name='Emails promocionales'),
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, help_text='Tu profesión o trabajo actual', max_length=100, verbose_name='Ocupación'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Solo números, sin espacios ni guiones', max_length=15, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe contener entre 7 y 15 dígitos.', regex='^\\d{7,15}$')], verbose_name='Número de teléfono'),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código postal'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_visible',
            field=models.BooleanField(default=True, help_text='Si tu perfil es visible para otros usuarios', verbose_name='Perfil público'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_email',
            field=models.BooleanField(default=False, help_text='Si otros usuarios pueden ver tu email', verbose_name='Mostrar email'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_phone',
            field=models.BooleanField(default=False, help_text='Si otros usuarios pueden ver tu teléfono', verbose_name='Mostrar teléfono'),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_notifications',
            field=models.BooleanField(default=False, help_text='Recibir notificaciones importantes por SMS', verbose_name='Notificaciones por SMS'),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_url',
            field=models.URLField(blank=True, verbose_name='Twitter/X'),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, help_text='Tu sitio web personal o profesional', verbose_name='Sitio web'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre completo'),
        ),
    ]
