# Generated by Django 5.1.11 on 2025-07-11 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_currency'),
        ('users', '0003_alter_user_options_user_address_user_avatar_user_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20, verbose_name='Status')),
                ('application_reason', models.TextField(help_text='Explica por qué quieres ser un proveedor/patrocinador en nuestra plataforma', max_length=1000, verbose_name='Razón de la aplicación')),
                ('company_name', models.CharField(max_length=200, verbose_name='Nombre de la empresa')),
                ('company_description', models.TextField(blank=True, max_length=1000, verbose_name='Descripción de la empresa')),
                ('company_size', models.CharField(blank=True, choices=[('startup', 'Startup (1-10 empleados)'), ('small', 'Pequeña (11-50 empleados)'), ('medium', 'Mediana (51-200 empleados)'), ('large', 'Grande (201-1000 empleados)'), ('enterprise', 'Empresa (1000+ empleados)')], max_length=20, verbose_name='Tamaño de la empresa')),
                ('industry', models.CharField(blank=True, choices=[('technology', 'Tecnología'), ('marketing', 'Marketing y Publicidad'), ('food', 'Alimentos y Bebidas'), ('fashion', 'Moda y Retail'), ('finance', 'Servicios Financieros'), ('health', 'Salud y Bienestar'), ('education', 'Educación'), ('entertainment', 'Entretenimiento'), ('sports', 'Deportes'), ('automotive', 'Automotriz'), ('real_estate', 'Bienes Raíces'), ('consulting', 'Consultoría'), ('manufacturing', 'Manufactura'), ('logistics', 'Logística y Transporte'), ('energy', 'Energía'), ('telecommunications', 'Telecomunicaciones'), ('media', 'Medios de Comunicación'), ('nonprofit', 'Organización Sin Fines de Lucro'), ('government', 'Gobierno'), ('other', 'Otro')], max_length=50, verbose_name='Industria')),
                ('founding_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de fundación')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='NIT/RUT')),
                ('legal_address', models.CharField(blank=True, max_length=255, verbose_name='Dirección legal')),
                ('business_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono empresarial')),
                ('business_email', models.EmailField(blank=True, max_length=254, verbose_name='Email empresarial')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Persona de contacto')),
                ('contact_position', models.CharField(blank=True, max_length=100, verbose_name='Cargo del contacto')),
                ('company_website', models.URLField(blank=True, verbose_name='Sitio web de la empresa')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter/X')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('company_logo', models.ImageField(blank=True, upload_to='suppliers/logos/', verbose_name='Logo de la empresa')),
                ('company_banner', models.ImageField(blank=True, upload_to='suppliers/banners/', verbose_name='Banner de la empresa')),
                ('brochure', models.FileField(blank=True, upload_to='suppliers/brochures/', verbose_name='Brochure/Catálogo')),
                ('sponsorship_budget_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Presupuesto mínimo de patrocinio')),
                ('sponsorship_budget_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Presupuesto máximo de patrocinio')),
                ('preferred_event_types', models.JSONField(blank=True, default=list, verbose_name='Tipos de eventos preferidos')),
                ('preferred_locations', models.JSONField(blank=True, default=list, verbose_name='Ubicaciones preferidas')),
                ('target_audience', models.TextField(blank=True, max_length=500, verbose_name='Audiencia objetivo')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas del administrador')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Razón de rechazo')),
                ('is_public', models.BooleanField(default=True, verbose_name='Perfil público')),
                ('allow_contact', models.BooleanField(default=True, verbose_name='Permitir contacto directo')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notificaciones por email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Administrador que revisó la aplicación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_supplier_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier Profile',
                'verbose_name_plural': 'Supplier Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('organizer', 'Organizador'), ('supplier', 'Proveedor/Patrocinador')], max_length=20, verbose_name='Rol solicitado')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('under_review', 'En revisión')], default='pending', max_length=20, verbose_name='Estado')),
                ('motivation', models.TextField(help_text='Explica por qué quieres este rol y cómo planeas usarlo', max_length=1000, verbose_name='Motivación')),
                ('experience', models.TextField(blank=True, help_text='Describe tu experiencia previa relacionada con este rol', max_length=1000, verbose_name='Experiencia relevante')),
                ('additional_info', models.TextField(blank=True, max_length=500, verbose_name='Información adicional')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas del administrador')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Razón de rechazo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_role_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role Application',
                'verbose_name_plural': 'Role Applications',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'role', 'status')},
            },
        ),
        migrations.CreateModel(
            name='SponsorshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_tier', models.CharField(choices=[('platinum', 'Platinum'), ('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze'), ('partner', 'Partner')], max_length=20, verbose_name='Nivel de patrocinio propuesto')),
                ('budget_offered', models.PositiveIntegerField(blank=True, null=True, verbose_name='Presupuesto ofrecido')),
                ('message', models.TextField(help_text='Explica por qué quieres patrocinar este evento y qué puedes ofrecer', max_length=1000, verbose_name='Mensaje')),
                ('special_requirements', models.TextField(blank=True, max_length=500, verbose_name='Requerimientos especiales')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('under_review', 'En revisión'), ('contracted', 'Contratado')], default='pending', max_length=20, verbose_name='Estado')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('organizer_notes', models.TextField(blank=True, verbose_name='Notas del organizador')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas del administrador')),
                ('final_tier', models.CharField(blank=True, choices=[('platinum', 'Platinum'), ('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze'), ('partner', 'Partner')], max_length=20, verbose_name='Nivel final')),
                ('contract_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Monto del contrato')),
                ('contract_notes', models.TextField(blank=True, verbose_name='Notas del contrato')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_applications', to='events.event')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sponsorship_applications', to=settings.AUTH_USER_MODEL)),
                ('supplier_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorship_applications', to='users.supplierprofile')),
            ],
            options={
                'verbose_name': 'Sponsorship Application',
                'verbose_name_plural': 'Sponsorship Applications',
                'ordering': ['-created_at'],
                'unique_together': {('supplier_profile', 'event')},
            },
        ),
    ]
