# Generated by Django 5.1.11 on 2025-07-12 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_supplierprofile_roleapplication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organizer_suspended',
            field=models.BooleanField(default=False, help_text='Si el rol de organizador está temporalmente suspendido', verbose_name='Rol de organizador suspendido'),
        ),
        migrations.AddField(
            model_name='user',
            name='organizer_suspended_by',
            field=models.ForeignKey(blank=True, help_text='Administrador que suspendió el rol de organizador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizer_suspensions_made', to=settings.AUTH_USER_MODEL, verbose_name='Suspendido por'),
        ),
        migrations.AddField(
            model_name='user',
            name='organizer_suspended_until',
            field=models.DateTimeField(blank=True, help_text='Fecha hasta la cual está suspendido el rol de organizador', null=True, verbose_name='Suspendido hasta'),
        ),
        migrations.AddField(
            model_name='user',
            name='organizer_suspension_reason',
            field=models.TextField(blank=True, help_text='Motivo de la suspensión del rol de organizador', verbose_name='Razón de suspensión de organizador'),
        ),
        migrations.AddField(
            model_name='user',
            name='supplier_suspended',
            field=models.BooleanField(default=False, help_text='Si el rol de proveedor está temporalmente suspendido', verbose_name='Rol de proveedor suspendido'),
        ),
        migrations.AddField(
            model_name='user',
            name='supplier_suspended_by',
            field=models.ForeignKey(blank=True, help_text='Administrador que suspendió el rol de proveedor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_suspensions_made', to=settings.AUTH_USER_MODEL, verbose_name='Suspendido por'),
        ),
        migrations.AddField(
            model_name='user',
            name='supplier_suspended_until',
            field=models.DateTimeField(blank=True, help_text='Fecha hasta la cual está suspendido el rol de proveedor', null=True, verbose_name='Suspendido hasta'),
        ),
        migrations.AddField(
            model_name='user',
            name='supplier_suspension_reason',
            field=models.TextField(blank=True, help_text='Motivo de la suspensión del rol de proveedor', verbose_name='Razón de suspensión de proveedor'),
        ),
    ]
